### ISSUE TITLE
Unable to build the package

### ISSUE THREAD

**Issue by richiesgr** [metamx/druid-spark-batch#67]
Hi
I can't build as I can't found the package as the spark-1.5.2-mmx when I try to use the existing artifact 1.5.2 the compilation failed.
1/ Where the source or how can I build this artifact ?
2/ If I use this artifact is it working with a standard spark cluster that doesn't includes this

Thanks

**Comment by drcrallen** [comment]
Good question: https://github.com/metamx/spark/tree/v1.5.2-mmx

You should be able to replace the version in build.sbt with vanilla 1.6.1

**Comment by drcrallen** [comment]
See https://github.com/metamx/druid-spark-batch/issues/71for related
