### ISSUE TITLE
 Could not find artifact io.druid.extensions:druid-spark-batch

### ISSUE THREAD

**Issue by benwck** [metamx/druid-spark-batch#71]
Hi,
Seems like druid-spark-batch is not present in https://repo1.maven.org/maven2/io/druid/extensions/ ...
Any help ?

**Comment by benwck** [comment]
"-h org.apache.spark:spark-core_2.10:1.5.2-mmx4 and -c io.druid.extensions:druid-spark-batch_2.10:0.9.1-0" options don't work for me btw. :'(

Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache.spark:spark-core_2.10:jar:1.5.2-mx4 in  (https://repo1.maven.org/maven2/)

Bad config repo for me ?

**Comment by drcrallen** [comment]
The spark mmx stuff is not published to maven central. See https://groups.google.com/d/msg/druid-development/MqcAqCFnFDI/h8WyldHlCgAJ for more conversation on the matter.

**Comment by drcrallen** [comment]
Before this moves to druid.io proper, it will have better/clearer dependencies.
