### ISSUE TITLE
What is spark mmx version

### ISSUE THREAD

**Issue by richiesgr** [metamx/druid-spark-batch#81]
Hi

I'm using spark but I can't build nor using this extension because I can't find any info on a spark mmx version please help 
I'm using spark 1.6.1 bundle with ec2 script 
I'm using imply 1.3.0 based on druid 0.9.1.1

Thanks

**Comment by drcrallen** [comment]
Sorry, this went unnoticed. we have our own spark we use at https://github.com/metamx/spark . Right now https://github.com/metamx/spark/tree/v1.5.2-mmx4 is in use.

I'm working on fixing things so that spark2.0 will work with this.

**Comment by drcrallen** [comment]
Spark 1.6.x should work out of the box though.

**Comment by richiesgr** [comment]
Thanks I'll try now with 1.6.2 waiting for spark 2.0
